CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,

    name VARCHAR(100) NOT NULL,

    email VARCHAR(150) NOT NULL UNIQUE,

    password VARCHAR(255) NOT NULL,

    init_time TIMESTAMP NOT NULL,

    end_time TIMESTAMP,

    roles VARCHAR(20) NOT NULL DEFAULT 'GRATIS'
);
